feat:update grub config to add hugepages
beskar-cloud/infra-config pull request #4
Opened 2023-08-22 07:18 UTC by hemantsonawane95

2023-08-22 13:07 UTC, freznicek requested changes
few details need to be tweaked, see details in code.

2023-08-22 13:07 UTC, freznicek commented on roles/grub/tasks/main.yml
> +    content: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ grub_config.cmdline_linux_default | join(' ') }}\""
`grub_config.cmdline_linux_default` is variable which may not be defined (above you define it as the group_vars vairable for subset of nodes), therefore I'd except `when` keyword in this task similar to the task above (line 5)

2023-08-23 08:53 UTC, hemantsonawane95 commented on roles/grub/tasks/main.yml
> +  notify: update-grub
done

2023-08-23 10:44 UTC, freznicek approved these changes
LGTM

2023-08-23 10:48 UTC, merged